import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import ReactECharts from 'echarts-for-react';
import cytoscape from 'cytoscape';
import { AlertTriangle, ArrowUpRight, Download, Network, RefreshCw, Search, Upload, Play, Pause, RotateCcw, ShieldCheck } from 'lucide-react';
import { api, apiService } from '../services/api';
import { DataTable, type Column } from './common/DataTable';
import { Panel } from './common/Panel';
import { Badge } from './common/Badge';
import { formatBytes, formatDuration } from '../utils/formatters';
import type { Flow, Alert, Host } from '../types';

const POLL = 15000;
const colors = ['#34d399', '#60a5fa', '#a78bfa', '#fbbf24', '#fb7185'];
const read = async <T,>(url: string) => (await api.get<T>(url)).data;
function message(error: unknown): string {
  if (typeof error === 'object' && error && 'response' in error) {
    const response = (error as {response?: {data?: {detail?: unknown}}}).response;
    if (response?.data?.detail) return typeof response.data.detail === 'string' ? response.data.detail : JSON.stringify(response.data.detail);
  }
  return error instanceof Error ? error.message : 'Request failed. Check the backend connection.';
}
export function Page({title, description, children, action}: {title: string; description: string; children: ReactNode; action?: ReactNode}) {
  return <div className="workspace-page"><header className="page-heading"><div><div className="eyebrow">NETRA / SECURITY OPERATIONS</div><h1>{title}</h1><p>{description}</p></div>{action}</header>{children}</div>;
}
export function QueryState({queries}: {queries: {isPending: boolean; isError: boolean; error: unknown; refetch: () => unknown}[]}) {
  const failed = queries.find(q => q.isError);
  if (failed) return <div className="notice error" role="alert"><AlertTriangle size={18}/><span>{message(failed.error)}</span><button onClick={() => queries.forEach(q => q.refetch())}>Retry</button></div>;
  if (queries.some(q => q.isPending)) return <div className="notice" role="status"><RefreshCw size={16} className="animate-spin"/>Loading records from the API...</div>;
  return null;
}
function exportJSON(name: string, records: unknown) {
  const url = URL.createObjectURL(new Blob([JSON.stringify(records, null, 2)], {type: 'application/json'}));
  const a = document.createElement('a'); a.href = url; a.download = `netra-${name}.json`; a.click(); URL.revokeObjectURL(url);
}
function Toolbar({search, setSearch, count, records}: {search: string; setSearch: (s: string) => void; count: number; records: unknown}) {
  return <div className="toolbar"><label className="search-field"><Search size={16}/><input aria-label="Filter records" placeholder="Filter visible records by any field..." value={search} onChange={e => setSearch(e.target.value)}/></label><span className="muted">{count} records</span><button className="button" onClick={() => exportJSON('records', records)}><Download size={15}/>Export JSON</button></div>;
}
const filter = <T,>(data: T[], search: string) => data.filter(row => JSON.stringify(row).toLowerCase().includes(search.toLowerCase()));
const stamp = (value: string) => new Date(value).toLocaleString();
const flowColumns: Column<Flow>[] = [
  {key:'timestamp',header:'Observed',render:f=>stamp(f.timestamp)},
  {key:'srcIp',header:'Source',render:f=><span className="font-mono text-blue-300">{f.srcIp}:{f.srcPort}</span>},
  {key:'dstIp',header:'Destination',render:f=><span className="font-mono text-emerald-300">{f.dstIp}:{f.dstPort}</span>},
  {key:'protocol',header:'Protocol'}, {key:'appProtocol',header:'Application'},
  {key:'packets',header:'Packets'}, {key:'bytes',header:'Transferred',render:f=>formatBytes(f.bytes)},
  {key:'duration',header:'Duration',render:f=>formatDuration(f.duration)},
  {key:'riskScore',header:'Risk',render:f=><Risk score={f.riskScore}/>}, {key:'attackType',header:'Detection'},
];
function Risk({score}: {score: number}) {return <span className={`font-mono font-semibold ${score >= 80 ? 'text-red-400' : score >= 50 ? 'text-amber-400' : 'text-emerald-400'}`}>{score.toFixed(1)}</span>;}
function FlowTable({data}: {data: Flow[]}) {return <div className="table-card"><DataTable data={data} columns={flowColumns} keyExtractor={f=>f.id} emptyMessage="No flows match this view."/></div>;}
function TrafficChart({flows}: {flows: Flow[]}) {
  const buckets = new Map<string, number>();
  [...flows].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).forEach(f=>{const time = new Date(f.timestamp); time.setSeconds(0,0); const k=time.toISOString(); buckets.set(k,(buckets.get(k)||0)+f.bytes);});
  return <ReactECharts style={{height:265}} option={{color:colors,tooltip:{trigger:'axis'},grid:{left:70,right:20,top:20,bottom:35},xAxis:{type:'category',data:[...buckets.keys()].map(t=>new Date(t).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})),axisLabel:{color:'#94a3b8'}},yAxis:{type:'value',name:'bytes / minute',nameTextStyle:{color:'#94a3b8'},axisLabel:{color:'#94a3b8'},splitLine:{lineStyle:{color:'#1e293b'}}},series:[{type:'line',smooth:true,data:[...buckets.values()],areaStyle:{opacity:0.12},symbol:'none'}]}}/>;
}
export function DashboardPage() {
  const summary=useQuery({queryKey:['summary'],queryFn:apiService.getDashboardSummary,refetchInterval:POLL});
  const flows=useQuery({queryKey:['flows'],queryFn:apiService.getFlows,refetchInterval:POLL});
  const hosts=useQuery({queryKey:['hosts'],queryFn:apiService.getHosts,refetchInterval:POLL});
  const incidents=useQuery({queryKey:['incidents'],queryFn:apiService.getIncidents,refetchInterval:POLL});
  const protocols: Record<string,number>={}; (flows.data?.data||[]).forEach(f=>{protocols[f.appProtocol||f.protocol]=(protocols[f.appProtocol||f.protocol]||0)+1;});
  return <Page title="Network overview" description="Traffic evidence, asset exposure, and investigation activity in one workspace." action={<Link className="button primary" to="topology"><Network size={16}/>Explore network</Link>}>
    <QueryState queries={[summary,flows,hosts,incidents]}/>
    <div className="stat-grid">{[['Active incidents',summary.data?.activeIncidents],['Critical alerts',summary.data?.criticalAlerts],['Observed hosts',summary.data?.totalHosts],['Stored flows',summary.data?.totalFlows],['Forecast risk',summary.data?.forecastRiskLevel]].map(([label,value])=><div className="stat-card" key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>
    <div className="chart-grid"><Panel title="Observed traffic volume"><TrafficChart flows={flows.data?.data||[]}/><p className="muted">Aggregated from the most recent {flows.data?.data.length||0} flow records, not live bandwidth.</p></Panel><Panel title="Protocol distribution"><ReactECharts style={{height:285}} option={{color:colors,tooltip:{trigger:'item'},legend:{bottom:0,textStyle:{color:'#94a3b8'}},series:[{type:'pie',radius:['45%','70%'],label:{show:false},data:Object.entries(protocols).map(([name,value])=>({name,value}))}]}}/></Panel></div>
    <div className="chart-grid"><Panel title="Highest risk assets" noPadding><DataTable data={[...(hosts.data?.data||[])].sort((a,b)=>b.riskScore-a.riskScore).slice(0,6)} keyExtractor={h=>h.id} columns={[{key:'hostname',header:'Host',render:h=><Link className="link" to="assets">{h.hostname||h.ip}</Link>},{key:'ip',header:'IP address'},{key:'deviceType',header:'Type'},{key:'riskScore',header:'Risk',render:h=><Risk score={h.riskScore}/>}]}/></Panel><Panel title="Recent incidents" noPadding><DataTable data={(incidents.data?.data||[]).slice(0,6)} keyExtractor={i=>i.id} columns={[{key:'title',header:'Investigation',render:i=><Link className="link" to={`/incidents/${i.id}`}>{i.title}</Link>},{key:'severity',header:'Severity',render:i=><Badge variant={i.severity}>{i.severity}</Badge>},{key:'status',header:'Status'}]}/></Panel></div>
  </Page>;
}
export function FlowsPage({kind='all'}: {kind?: 'all'|'dns'|'tls'|'packets'}) {
  const query=useQuery({queryKey:['flows'],queryFn:apiService.getFlows,refetchInterval:POLL});
  const [search,setSearch]=useState('');
  const scoped=(query.data?.data||[]).filter(f=>kind==='dns' ? f.dstPort===53||f.srcPort===53||f.appProtocol==='DNS' : kind==='tls' ? f.dstPort===443||f.srcPort===443||f.appProtocol==='TLS' : true);
  const rows=filter(scoped,search);
  const titles={all:'Flow explorer',dns:'DNS traffic',tls:'TLS traffic',packets:'Packet metadata'};
  return <Page title={titles[kind]} description={kind==='packets' ? 'Flow-level packet counts and transfer metadata. Raw packet payloads and PCAP capture are not available.' : kind==='dns' ? 'DNS-associated flows by port and application protocol. Query names require a DNS sensor integration.' : kind==='tls' ? 'TLS-associated flows by port and application protocol. Certificate inspection is not configured.' : 'Inspect persisted traffic records, search evidence, and export your current view.'}>
    <QueryState queries={[query]}/><Toolbar search={search} setSearch={setSearch} count={rows.length} records={rows}/><FlowTable data={rows}/><p className="muted">Showing up to 500 recent records of {query.data?.total||0} stored flows. Use the paginated API for the full dataset.</p>
  </Page>;
}
export function AlertsPage() {
  const query=useQuery({queryKey:['alerts'],queryFn:apiService.getAlerts,refetchInterval:POLL});
  const client=useQueryClient(); const [search,setSearch]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState<string|null>(null);
  const rows=filter(query.data?.data||[],search);
  async function update(a: Alert,status: string) {setBusy(a.id);setError('');try {await api.patch(`/alerts/${a.id}`,{status});await client.invalidateQueries();}catch(e){setError(message(e));}finally{setBusy(null);}}
  return <Page title="Detection alerts" description="Review rule-generated evidence and track analyst acknowledgement."><QueryState queries={[query]}/>{error&&<div className="notice error" role="alert">{error}</div>}<Toolbar search={search} setSearch={setSearch} count={rows.length} records={rows}/><div className="table-card"><DataTable data={rows} keyExtractor={a=>a.id} columns={[{key:'timestamp',header:'Observed',render:a=>stamp(a.timestamp)},{key:'severity',header:'Severity',render:a=><Badge variant={a.severity}>{a.severity}</Badge>},{key:'signature',header:'Detection'},{key:'srcIp',header:'Source'},{key:'dstIp',header:'Destination'},{key:'source',header:'Engine'},{key:'status',header:'Status',render:a=><select aria-label={`Status for ${a.id}`} value={a.status} disabled={busy===a.id} onChange={e=>update(a,e.target.value)}>{['new','acknowledged','resolved'].map(s=><option key={s}>{s}</option>)}</select>}]}/></div></Page>;
}
export function IncidentsPage() {
  const query=useQuery({queryKey:['incidents'],queryFn:apiService.getIncidents,refetchInterval:POLL}); const [search,setSearch]=useState(''); const rows=filter(query.data?.data||[],search);
  return <Page title="Incident investigations" description="Correlated detections grouped into investigations with persistent lifecycle state."><QueryState queries={[query]}/><Toolbar search={search} setSearch={setSearch} count={rows.length} records={rows}/><div className="table-card"><DataTable data={rows} keyExtractor={i=>i.id} columns={[{key:'title',header:'Investigation',render:i=><Link className="link" to={`/incidents/${i.id}`}>{i.title}<ArrowUpRight size={12} className="inline ml-2"/></Link>},{key:'severity',header:'Severity',render:i=><Badge variant={i.severity}>{i.severity}</Badge>},{key:'stage',header:'Stage'},{key:'status',header:'Status'},{key:'affectedHosts',header:'Hosts',render:i=>i.affectedHosts.length},{key:'updatedAt',header:'Updated',render:i=>stamp(i.updatedAt)}]}/></div></Page>;
}
export function IncidentDetail() {
  const {id}=useParams(); const client=useQueryClient(); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const query=useQuery({queryKey:['incident',id],queryFn:()=>apiService.getIncident(id!)});
  const alerts=useQuery({queryKey:['alerts'],queryFn:apiService.getAlerts}); const hosts=useQuery({queryKey:['hosts'],queryFn:apiService.getHosts}); const incident=query.data;
  const affected=(hosts.data?.data||[]).filter(h=>incident?.affectedHosts.includes(h.id)||incident?.affectedHosts.includes(h.ip));
  const related=(alerts.data?.data||[]).filter(a=>affected.some(h=>h.ip===a.srcIp||h.ip===a.dstIp));
  async function update(status:string){setBusy(true);try{await api.patch(`/incidents/${id}`,{status});await client.invalidateQueries();setError('');}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <Page title={incident?.title||'Incident details'} description="Review the observed stage, affected assets, and associated evidence." action={<Link className="button" to="/incidents">All incidents</Link>}><QueryState queries={[query,alerts,hosts]}/>{error&&<div role="alert" className="notice error">{error}</div>}{incident&&<><Panel title="Investigation state"><div className="toolbar"><Badge variant={incident.severity}>{incident.severity}</Badge><span>{incident.stage}</span><select aria-label="Incident status" disabled={busy} value={incident.status} onChange={e=>update(e.target.value)}>{['active','investigating','mitigated','closed'].map(s=><option key={s}>{s}</option>)}</select><Link className="button" to={`/replay/${incident.id}`}><Play size={14}/>Event replay</Link></div><p className="muted">Created {stamp(incident.createdAt)} / Updated {stamp(incident.updatedAt)}</p></Panel><Panel title="Affected hosts"><div className="flex flex-wrap gap-3">{affected.map(h=><Link className="button" key={h.id} to="/topology">{h.hostname||h.ip} / {h.ip}</Link>)}</div></Panel><Panel title="Alerts involving affected hosts" noPadding><DataTable data={related} keyExtractor={a=>a.id} columns={[{key:'timestamp',header:'Observed',render:a=>stamp(a.timestamp)},{key:'signature',header:'Evidence'},{key:'severity',header:'Severity',render:a=><Badge variant={a.severity}>{a.severity}</Badge>},{key:'mitreTechnique',header:'Technique'}]}/></Panel></>}</Page>;
}
export function ForecastPage() {
  const query=useQuery({queryKey:['forecast'],queryFn:apiService.getCurrentForecast,refetchInterval:POLL}); const f=query.data;
  return <Page title="Attack-stage forecast" description="Explainable heuristic estimates from observed detections. Scores are not calibrated probabilities or validated ML predictions." action={<Link to="/topology" className="button"><Network size={16}/>Network map</Link>}><QueryState queries={[query]}/>{f&&<><div className="stat-grid"><div className="stat-card"><span>Observed stage</span><strong>{f.currentStage}</strong></div><div className="stat-card"><span>Heuristic stage confidence</span><strong>{(f.stageConfidence*100).toFixed(0)}%</strong></div><div className="stat-card"><span>Updated</span><strong className="small-stat">{stamp(f.timestamp)}</strong></div></div><div className="chart-grid"><Panel title="Next-stage heuristic weights"><ReactECharts style={{height:330}} option={{tooltip:{trigger:'axis'},grid:{left:140,right:30,bottom:30,top:20},xAxis:{type:'value',max:1,axisLabel:{color:'#94a3b8'},splitLine:{lineStyle:{color:'#1e293b'}}},yAxis:{type:'category',data:f.nextStages.map(s=>s.stage),axisLabel:{color:'#cbd5e1'}},series:[{type:'bar',data:f.nextStages.map(s=>s.probability),itemStyle:{color:'#34d399',borderRadius:[0,4,4,0]},label:{show:true,position:'right',color:'#cbd5e1',formatter:(p:{value:number})=>`${(p.value*100).toFixed(0)}%`}}]}}/></Panel><Panel title="Potential target ranking"><div className="space-y-5">{f.targetPredictions.map(t=><div key={t.hostId}><div className="flex justify-between mb-2"><span className="font-mono">{t.ip}</span><span className="text-amber-300">{(t.probability*100).toFixed(0)}%</span></div><div className="h-2 rounded bg-slate-800"><div className="h-2 bg-amber-400 rounded" style={{width:`${Math.max(0,Math.min(100,t.probability*100))}%`}}/></div></div>)}{!f.targetPredictions.length&&<p className="muted">No target evidence is currently available.</p>}</div></Panel></div><div className="notice"><ShieldCheck size={20}/><span>This baseline supports investigation prioritization. Confirm hypotheses with the alert evidence before taking action.</span></div></>}</Page>;
}
export function AssetsPage() {
  const query=useQuery({queryKey:['hosts'],queryFn:apiService.getHosts,refetchInterval:POLL}); const [search,setSearch]=useState(''); const rows=filter(query.data?.data||[],search);
  return <Page title="Asset inventory" description="Hosts observed in stored traffic, their current risk, and discovery metadata."><QueryState queries={[query]}/><Toolbar search={search} setSearch={setSearch} count={rows.length} records={rows}/><div className="table-card"><DataTable data={rows} keyExtractor={h=>h.id} columns={[{key:'hostname',header:'Host',render:h=>h.hostname||h.id},{key:'ip',header:'IP address'},{key:'deviceType',header:'Device type'},{key:'criticality',header:'Criticality',render:h=><Badge variant={h.criticality}>{h.criticality}</Badge>},{key:'riskScore',header:'Risk',render:h=><Risk score={h.riskScore}/>},{key:'lastSeen',header:'Last seen',render:h=>stamp(h.lastSeen)}]}/></div></Page>;
}
export function TopologyPage() {
  const query=useQuery({queryKey:['topology'],queryFn:apiService.getTopologyGraph,refetchInterval:POLL});
  const hosts=useQuery({queryKey:['hosts'],queryFn:apiService.getHosts}); const container=useRef<HTMLDivElement>(null); const cy=useRef<cytoscape.Core|null>(null);
  const [layout,setLayout]=useState('cose'); const [scope,setScope]=useState('all'); const [search,setSearch]=useState(''); const [selected,setSelected]=useState<Host|undefined>();
  useEffect(()=>{
    if(!container.current||!query.data)return;
    const graph=query.data;
    const matches=new Set(graph.nodes.filter(n=>`${n.data.label} ${n.data.id} ${(hosts.data?.data||[]).find(h=>h.id===n.data.id)?.ip||''}`.toLowerCase().includes(search.toLowerCase())).map(n=>n.data.id));
    const nodes=graph.nodes.filter(n=>matches.has(n.data.id)); const edges=graph.edges.filter(e=>matches.has(e.data.source)&&matches.has(e.data.target)&&(scope==='all'||(scope==='risk' ? e.data.risk>=60 : e.data.isForecastPath)));
    const instance=cytoscape({container:container.current,elements:[...nodes,...edges],layout:{name:layout,animate:false,padding:50},minZoom:0.15,maxZoom:4,style:[
      {selector:'node',style:{label:'data(label)','font-size':11,color:'#cbd5e1','text-valign':'bottom','text-margin-y':9,'background-color':'#0f2431','border-width':2,'border-color':'#34d399',width:34,height:34}},
      {selector:'node[risk >= 60]',style:{'border-color':'#fb923c','background-color':'#593628'}},
      {selector:'node[risk >= 80]',style:{'border-color':'#fb7185','background-color':'#5b2333'}},
      {selector:'node:selected',style:{'border-width':5,'border-color':'#60a5fa'}},
      {selector:'edge',style:{width:1.5,'line-color':'#334155','target-arrow-color':'#334155','target-arrow-shape':'triangle','curve-style':'bezier'}},
      {selector:'edge[risk >= 60]',style:{'line-color':'#fb7185','target-arrow-color':'#fb7185',width:2}},
      {selector:'edge[?isForecastPath]',style:{'line-style':'dashed','line-color':'#fbbf24','target-arrow-color':'#fbbf24'}}
    ]}); cy.current=instance;
    instance.on('tap','node',e=>setSelected((hosts.data?.data||[]).find(h=>h.id===e.target.id())));
    const observer=new ResizeObserver(()=>{instance.resize();});observer.observe(container.current);
    return()=>{observer.disconnect();instance.destroy();cy.current=null;};
  },[query.data,hosts.data,layout,scope,search]);
  return <Page title="Network topology" description="A logical communication map from stored flows. Drag nodes, scroll to zoom, or select an asset for details."><QueryState queries={[query,hosts]}/><div className="toolbar"><label className="search-field"><Search size={16}/><input aria-label="Find topology nodes" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find host or IP..."/></label><select aria-label="Graph layout" value={layout} onChange={e=>setLayout(e.target.value)}><option value="cose">Force layout</option><option value="breadthfirst">Hierarchy</option><option value="concentric">Radial</option><option value="circle">Circle</option></select><select aria-label="Graph scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="all">All communications</option><option value="risk">High risk links</option><option value="forecast">Forecast links</option></select><button className="button" onClick={()=>cy.current?.fit(undefined,50)}>Fit map</button><button className="button" onClick={()=>{if(cy.current){const a=document.createElement('a');a.href=cy.current.png({bg:'#080f1d',full:true,scale:2});a.download='netra-topology.png';a.click();}}}><Download size={15}/>PNG</button></div><div className="network-shell"><div ref={container} className="network-canvas" role="img" aria-label="Interactive network topology graph"/><aside className="network-detail"><h3>Map legend</h3><p><span className="text-emerald-300">Green</span> / Risk below 60</p><p><span className="text-orange-300">Orange</span> / Risk 60–79</p><p><span className="text-rose-300">Red</span> / Risk 80–100</p><p><span className="text-amber-300">Dashed</span> / Heuristic forecast</p><hr/><label className="block mb-2">Inspect asset<select aria-label="Inspect topology asset" className="w-full mt-2" value={selected?.id||''} onChange={e=>setSelected(hosts.data?.data.find(h=>h.id===e.target.value))}><option value="">Select a host</option>{(hosts.data?.data||[]).map(h=><option value={h.id} key={h.id}>{h.hostname||h.ip}</option>)}</select></label>{selected?<><h3>{selected.hostname||selected.ip}</h3><p className="font-mono">{selected.ip}</p><p>{selected.deviceType}</p><p>Risk: <Risk score={selected.riskScore}/></p><p>Last seen {stamp(selected.lastSeen)}</p><Link className="link" to="/flows">Inspect flows</Link></>:<p>Select a node or choose an asset to inspect its observed identity.</p>}</aside></div></Page>;
}
export function HuntingPage() {
  const [query,setQuery]=useState('riskScore >= 60'); const [data,setData]=useState<Flow[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [ran,setRan]=useState(false);
  async function run(){setBusy(true);setError('');try{const result=await api.post<{data:Flow[]}>('/hunting/query',{query});setData(result.data.data);setRan(true);}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <Page title="Threat hunting" description="Query persisted flows with a constrained expression language; results come from the backend."><form className="toolbar" onSubmit={e=>{e.preventDefault();run();}}><input className="flex-1 font-mono" aria-label="Hunting query" value={query} onChange={e=>setQuery(e.target.value)}/><button className="button primary" disabled={busy} type="submit"><Search size={16}/>{busy?'Running...':'Run query'}</button><button className="button" type="button" onClick={()=>exportJSON('hunting',data)}><Download size={15}/>Export</button></form><p className="muted">Examples: riskScore &gt;= 60 · protocol == "TCP" and bytes &gt; 10000 · dstPort == 53</p>{error&&<div className="notice error" role="alert">{error}</div>}{ran?<><p className="muted">{data.length} matching flows</p><Panel title="Matching traffic over time"><TrafficChart flows={data}/></Panel><FlowTable data={data}/></>:<div className="empty-state"><Search size={36}/><h2>Start an evidence-led investigation</h2><p>Run a query to inspect matching traffic and its timeline.</p></div>}</Page>;
}
export function MitrePage() {
  const query=useQuery({queryKey:['alerts'],queryFn:apiService.getAlerts}); const [selected,setSelected]=useState<string|null>(null); const alerts=query.data?.data||[];
  const tactics=[...new Set(alerts.map(a=>a.mitreTactic).filter((v):v is string=>Boolean(v)))];
  return <Page title="ATT&CK evidence map" description="Observed tactic and technique labels attached to detections. This is an evidence map, not full ATT&CK coverage."><QueryState queries={[query]}/><div className="mitre-grid">{tactics.map(t=><Panel key={t} title={t}><div className="space-y-2">{[...new Set(alerts.filter(a=>a.mitreTactic===t).map(a=>a.mitreTechnique||'Unmapped'))].map(tech=><button className={`technique ${selected===tech?'selected':''}`} key={tech} onClick={()=>setSelected(selected===tech?null:tech)}>{tech}<span>{alerts.filter(a=>a.mitreTechnique===tech).length} detections</span></button>)}</div></Panel>)}</div>{!tactics.length&&!query.isPending&&<div className="notice">No technique mappings are available.</div>}{selected&&<Panel title={`Evidence / ${selected}`}><ul className="space-y-3">{alerts.filter(a=>a.mitreTechnique===selected).map(a=><li key={a.id}><Badge variant={a.severity}>{a.severity}</Badge> <Link to="/alerts" className="link">{a.signature}</Link><p className="muted">{a.srcIp} to {a.dstIp} / {stamp(a.timestamp)}</p></li>)}</ul></Panel>}</Page>;
}
export function HealthPage() {
  const query=useQuery({queryKey:['health'],queryFn:apiService.getHealth,refetchInterval:POLL}); const h=query.data;
  return <Page title="System health" description="Current service readiness and host resource readings reported by the API." action={<button className="button" onClick={()=>query.refetch()}><RefreshCw size={15}/>Refresh</button>}><QueryState queries={[query]}/>{h&&<><div className="stat-grid"><div className="stat-card"><span>Overall status</span><strong>{h.status}</strong></div>{Object.entries(h.components).map(([name,value])=><div className="stat-card" key={name}><span>{name}</span><strong className={value==='up'?'text-emerald-300':'text-amber-300'}>{value}</strong></div>)}</div><Panel title="Host resource usage"><div className="space-y-6">{Object.entries(h.metrics).map(([name,value])=><div key={name}><div className="flex justify-between mb-2"><span className="uppercase text-xs">{name}</span><span>{value.toFixed(1)}%</span></div><div className="h-2 bg-slate-800 rounded"><div className="h-2 bg-blue-400 rounded" style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>)}</div></Panel><div className="notice">Capture is reported down when no live sensor is attached. Stored-data analysis and imports remain available. The inference component reports the heuristic engine, not a trained production model.</div></>}</Page>;
}
type Settings={profile:string;retentionDays:number;autoRefresh:boolean;demoMode:boolean};
export function SettingsPage() {
  const query=useQuery({queryKey:['settings'],queryFn:()=>read<Settings>('/settings')}); const client=useQueryClient(); const [form,setForm]=useState<Settings|null>(null); const [status,setStatus]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [payload,setPayload]=useState('');
  useEffect(()=>{if(query.data)setForm(query.data);},[query.data]);
  async function save(){if(!form)return;setBusy(true);setError('');setStatus('');try{await api.patch('/settings',{profile:form.profile,retentionDays:form.retentionDays,autoRefresh:form.autoRefresh});await client.invalidateQueries({queryKey:['settings']});setStatus('Settings saved.');}catch(e){setError(message(e));}finally{setBusy(false);}}
  async function ingest(){setBusy(true);setError('');setStatus('');try{const parsed=JSON.parse(payload);const result=await api.post('/ingest/flows',Array.isArray(parsed)?{flows:parsed}:parsed);await client.invalidateQueries();setStatus(`Import completed: ${JSON.stringify(result.data)}`);}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <Page title="Settings & data import" description="Persist workspace settings and ingest flow JSON for analysis."><QueryState queries={[query]}/>{error&&<div className="notice error" role="alert">{error}</div>}{status&&<div className="notice" role="status">{status}</div>}{form&&<Panel title="Stored preferences"><form className="settings-form" onSubmit={e=>{e.preventDefault();save();}}><label>Profile<select value={form.profile} onChange={e=>setForm({...form,profile:e.target.value})}><option>STANDARD</option><option>LITE</option><option>FULL</option></select></label><label>Retention preference (days)<input type="number" min={1} max={365} value={form.retentionDays} onChange={e=>setForm({...form,retentionDays:Number(e.target.value)})}/></label><label className="checkbox-label"><input type="checkbox" checked={form.autoRefresh} onChange={e=>setForm({...form,autoRefresh:e.target.checked})}/>Refresh dashboard data automatically</label><p className="muted">Profile and retention are stored preferences; they do not provision capture services or delete historical data.</p><button className="button primary" disabled={busy}>Save preferences</button></form></Panel>}<Panel title="Import flow records"><p className="muted mb-3">Upload JSON or paste an array of flows. Required fields: srcIp, dstIp, srcPort, dstPort, protocol, packets, bytes, duration (milliseconds). Optional timestamp uses ISO 8601.</p><label className="button w-fit mb-3"><Upload size={15}/>Choose JSON<input type="file" className="sr-only" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>5*1024*1024){setError('Select a JSON file smaller than 5 MB.');return;}setPayload(await file.text());}}}/></label><textarea aria-label="Flow JSON to import" rows={8} className="w-full font-mono text-xs" value={payload} onChange={e=>setPayload(e.target.value)} placeholder={'[{"srcIp":"10.0.0.10","dstIp":"10.0.0.20","srcPort":52000,"dstPort":443,"protocol":"TCP","packets":10,"bytes":2048,"duration":150}]'}/><button className="button primary mt-3" disabled={busy||!payload.trim()} onClick={ingest}><Upload size={15}/>Import and analyze</button></Panel></Page>;
}
type ReplayEvent={timestamp:string;type:string;title:string;entityId:string;source:string};
export function ReplayPage() {
  const {id}=useParams(); const query=useQuery({queryKey:['replay',id],queryFn:()=>read<{events:ReplayEvent[];total:number}>(id?`/replay?incidentId=${encodeURIComponent(id)}`:'/replay')});
  const [position,setPosition]=useState(0); const [playing,setPlaying]=useState(false); const [speed,setSpeed]=useState(1); const events=query.data?.events||[];
  useEffect(()=>{if(!playing)return;const timer=window.setInterval(()=>setPosition(p=>{if(p>=events.length){setPlaying(false);return p;}return p+1;}),1000/speed);return()=>clearInterval(timer);},[playing,speed,events.length]);
  return <Page title="Event replay" description="Step through persisted events in chronological order. Playback advances one recorded event per tick; no historical topology reconstruction is performed."><QueryState queries={[query]}/><div className="toolbar"><button className="button" aria-label="Reset replay" onClick={()=>{setPosition(0);setPlaying(false);}}><RotateCcw size={16}/></button><button className="button primary" disabled={!events.length} onClick={()=>{if(position>=events.length)setPosition(0);setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause':'Play'}</button><button className="button" disabled={position>=events.length} onClick={()=>{setPosition(p=>Math.min(events.length,p+1));setPlaying(false);}}>Next event</button><select aria-label="Replay speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[1,2,5].map(s=><option key={s} value={s}>{s} events / sec</option>)}</select><span className="muted">{position} / {events.length} events</span></div><input aria-label="Replay event position" type="range" min={0} max={events.length} value={position} onChange={e=>{setPosition(Number(e.target.value));setPlaying(false);}} className="w-full accent-emerald-400"/><div className="timeline">{events.slice(0,position).map((event,i)=><div className="timeline-event" key={`${event.entityId}-${i}`}><span className="timeline-dot"/><div><span className="muted font-mono">{stamp(event.timestamp)}</span><h3>{event.title}</h3><p className="muted">{event.type} / {event.source} / {event.entityId}</p></div></div>)}{!position&&<div className="empty-state"><Play size={30}/><p>Press Play or move the slider to review recorded evidence.</p></div>}</div></Page>;
}
export function DeceptionPage(){return <Page title="Deception integrations" description="Integration availability"><div className="empty-state"><ShieldCheck size={40}/><h2>No deception sensor connected</h2><p>Honeypot deployment and automated containment are not implemented in this baseline.</p><p>Import observed flow metadata from your sensor in Settings to analyze it alongside other evidence.</p><Link className="button primary" to="/settings"><Upload size={16}/>Import sensor data</Link></div></Page>;}
